services:
  medusa-i2v:
    container_name: medusa-i2v
    build: .
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 140G
    ports:
      - "8888:8888"
    volumes:
      - ./data:/workspace
    environment:
      - WORKSPACE=/workspace
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
